channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.1.2
- pip:
  - mlflow==2.11.3
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.0
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
  - typing-extensions==4.7.1
name: mlflow-env
